name: simple_ppo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2.6
  - matplotlib=3.10.8
  - libstdcxx-ng       # ensures compatible C++ runtime for pip packages
  - pip
  - pip:
    - gymnasium[classic-control,box2d]==1.2.3
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.10.0+cpu
